version: '3.8'

services:
  blockflow:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/blockflow
    stdin_open: true  # Keep container running
    tty: true         # Allocate a pseudo-TTY